### ISSUE TITLE
Paramiko version

### ISSUE THREAD

**Issue by ric79** [QualiSystems/CloudShell-Utilities#1]
Hello,
when I try to run `Execute Command.py` I get: 

```
Exception: ('SSH Manager', 'Exception: global name \'descriptor\' is not defined
------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/00918220/PycharmProjects/untitled/SSHManager.py", line 49, in connect
    self._username, self._password, banner_timeout=self._timeout)
  File "C:\\Python27\\lib\\site-packages\\paramiko\\client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "C:\\Python27\\lib\\site-packages\\paramiko\\client.py", line 456, in _auth
    self._agent = Agent()
  File "C:\\Python27\\lib\\site-packages\\paramiko\\agent.py", line 340, in __init__
    self._connect(conn)
  File "C:\\Python27\\lib\\site-packages\\paramiko\\agent.py", line 66, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "C:\\Python27\\lib\\site-packages\\paramiko\\agent.py", line 83, in _send_message
    self._conn.send(struct.pack(\'>I\', len(msg)) + msg)
  File "C:\\Python27\\lib\\site-packages\\paramiko\\win_pageant.py", line 123, in send
    self._response = _query_pageant(data)
  File "C:\\Python27\\lib\\site-packages\\paramiko\\win_pageant.py", line 89, in _query_pageant
    _winapi.get_security_attributes_for_user(),
  File "C:\\Python27\\lib\\site-packages\\paramiko\\_winapi.py", line 273, in get_security_attributes_for_user
    SA.descriptor = SD
  File "C:\\Python27\\lib\\site-packages\\paramiko\\_winapi.py", line 222, in descriptor
    self._descriptor = descriptor
NameError: global name \'descriptor\' is not defined
------------------------------------------------------------')
```

Could you tell me what is the right Paramiko version which I have to use?

I'm currently using:
`pip install paramiko==1.15.2`

**Comment by ric79** [comment]
I found a workaround: C:\Python27\Lib\site-packages\paramiko_winapi.py
From

```
    @descriptor.setter
    def descriptor(self, value):
        self._descriptor = descriptor
        self.lpSecurityDescriptor = ctypes.addressof(descriptor)
```

to

```
    @descriptor.setter
    def descriptor(self, value):
        self._descriptor = value
        self.lpSecurityDescriptor = ctypes.addressof(value)
```

However which version of Paramiko should I use?
R
